# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('ui', 'ui'),
        ('utils', 'utils'),
        ('core', 'core'),
        ('config', 'config'),
        ('config.ini.example', '.'),
        ('version.txt', '.')
    ],
    hiddenimports=[
        'customtkinter',
        'PIL._tkinter_finder',
        'requests',
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.kdf.pbkdf2',
        'threading',
        'queue',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'json',
        'configparser',
        'pathlib',
        'subprocess',
        'shutil',
        'zipfile',
        'tempfile',
        'datetime',
        'hashlib',
        'base64',
        'webbrowser',
        'platform',
        'getpass',
        'ui.ctk_generator_gui',
        'ui.strings',
        'utils.resource_utils',
        'utils.crypto_utils',
        'utils.version_utils',
        'utils.helpers',
        'core.package_generator',
        'core.github_manager',
        'config.config_manager',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'jupyter',
        'notebook',
        'IPython',
        'tornado',
        'zmq',
        'pygame',
        'cv2',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'wx',
        'tkinter.test',
        'test',
        'tests',
        'unittest',
        'doctest',
        'pydoc',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='unity-package-forge',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info.txt',
    icon='ui/icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='unity-package-forge',
)